server:
  port: 8092

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

oauth2:
  client-id: order
  client-secret: secret
  check-token-uri: http://localhost:8090/oauth/check_token
